### PR TITLE
Dev vdnursultan feature

### PR DESCRIPTION
**Pull request by snapp1**

### CODE REVIEW

**Comment by MulyukovAidar** [comment]
Built with 
Linux and macOS (Windows Git Bash)-
export NODE_OPTIONS=--openssl-legacy-provider

Windows command prompt-
set NODE_OPTIONS=--openssl-legacy-provider

Windows PowerShell-
$env:NODE_OPTIONS = "--openssl-legacy-provider"

**Comment by snapp1** [comment]
image

**Comment by snapp1** [comment]
to build visual run OS specific command:
**Linux and macOS (Windows Git Bash)-**
export NODE_OPTIONS=--openssl-legacy-provider


**Windows command prompt-**
set NODE_OPTIONS=--openssl-legacy-provider


**Windows PowerShell-**
$env:NODE_OPTIONS = "--openssl-legacy-provider"

**Comment by MulyukovAidar** [comment]
visual builds fine when building on dev machine

**Pull request merged**
