### PR TITLE
Version 2.0.3 with the ability to display canvas tooltips

### PR DESCRIPTION
**Pull request by AlexanderK79**
Adjusted the code, so it displays canvas tooltips.
This time by creating an interface named TooltipReportPageEnabledDataPoint (which is created by extending the interface TooltipEnabledDataPoint in the file interfaces.ts) 

Also... removed a typo in SelectionBuider.

Hopefully this adjustment will pass the automatic tests.

### CODE REVIEW

**Comment by AlexanderK79** [comment]
There is a missing semicolon on line 2858 in the file gantt.ts

What is the easiest way to fix this, so the PR can be submitted?

**Comment by AlexanderK79** [comment]
it does not pass the Travis CI build.... let me double-check...

**Comment by AlexanderK79** [comment]
OK.... it is ready to be reviewed :-)

**Comment by AlexanderK79** [comment]
@helen508light what do you want me to do with this PR?
Wait until the new version is released? Or integrate the feature in the current version of the upstream/master branch?

**Comment by pbicvsupport** [comment]
@AlexanderK79 Please, make rebase
Now we are waiting for release version with fixed issues

**Pull request closed without merging**
