### PR TITLE
Canvas tooltips added in version 2.0.3

### PR DESCRIPTION
**Pull request by AlexanderK79**
Adjusted the code, so the user can add visual tooltips

### CODE REVIEW

**Comment by AlexanderK79** [comment]
TS2339: Property 'identity' does not exist on type 'TooltipEnabledDataPoint'.
this error can be solved by editing the file node_modules\powerbi-visuals-utils-tooltiputils\lib\tooltipInterfaces.d.ts

export interface TooltipEnabledDataPoint {
    tooltipInfo?: powerbi.extensibility.VisualTooltipDataItem[];
    identity?: ISelectionId; //addition

}

**Comment by zBritva** [comment]
You can't edit files in node_modules.
Please, sync with master branch. I included your commits into another PR and merged. Visual is going to publication.

**Comment by uve** [comment]
@AlexanderK79, we'll publish v2.0.2 the hotfix first. Please create a separate PR for Report tooltips feature.

**Comment by AlexanderK79** [comment]
created a new, separate PR....

**Pull request closed without merging**
