### PR TITLE
Adding various color settings

### PR DESCRIPTION
**Pull request by PaulSainsbury**
Hi,
We needed to be able to change the color of the axis (both the line color, and the text), as well as being able to set the default color for the task bars.  We needed to change the background color of our reports to black, for display on a kiosk type screen, and the black axis, black text, and default color of the bars was too dark to be visible.

I'm not sure if I've quite handled it correctly, as this was the first time I have ever adjusted a PowerBI visualization.  Please let me know if there is anything I can do to improve the work, or if you have any questions about what I was trying to achieve.  I am hoping the changes make sense.
From
  Paul

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by PaulSainsbury** [comment]
Oops, updating the guid worked around my problem with CSS not updating while testing the component, but broke the tests.  I'll update the request and re-submit.

**Comment by MrMeison** [comment]
@PaulSainsbury,  thank you for your PR. Please resolve to conflict with latest master version. Also, you can't need update GIUD for testing of visual, please revert to the previous version.
More information about debugging of visuals: https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/usage.md

**Comment by PaulSainsbury** [comment]
Thanks @MrMeison , In the 4 months since I made this request, I've changed jobs, and don't have access to the tools required to work with Power BI visuals.  If this response had come in 2-3 weeks after the pull request was made, I would have been happy to assist.  Unfortunately after 4 months I've moved on and if the changes have benefit to the visualization, someone else will need to work on it now.

**Comment by savvinsergey** [comment]
Thanks @PaulSainsbury.   I merged your pull request with latest master version and your new settings will be published with new version of visual soon

**Comment by ignatvilesov** [comment]
This PR has been merged by #26

**Pull request closed without merging**
